API_KEY = ""
SECRET_KEY = ""

# Parameters
SYMBOL = "ETH_USDT"
POSITION_SIZE = 0.1
CONTRACT_SIZE = 30
GRID_LINES = 5
THRESHOLD_POSITION = CONTRACT_SIZE * GRID_LINES * 2
# Gridbot Settings
NUM_BUY_GRID_LINES = GRID_LINES
NUM_SELL_GRID_LINES = GRID_LINES
GRID_SIZE = 20


CHECK_ORDERS_FREQUENCY = 2
CLOSED_ORDER_STATUS = 'closed'
